package com.tathva17.tathva.tathva17.EventsData;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.ImageButton;

import com.huxq17.swipecardsview.SwipeCardsView;
import com.tathva17.tathva.tathva17.R;

import java.util.ArrayList;
import java.util.List;

public class EventsDetailsActivity extends AppCompatActivity {

    private int j = 0;
    private SwipeCardsView swipeCardsView;
    private List<EventsModel> modelList = new ArrayList<>();
    private ImageButton imageButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.activity_events_details);


        getSupportActionBar().hide();
        swipeCardsView = (SwipeCardsView) findViewById(R.id.swipeCardView);
        swipeCardsView.retainLastCard(false);
        swipeCardsView.enableSwipe(true);

        imageButton = (ImageButton) findViewById(R.id.closer);


        getData();

        imageButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                finish();
            }
        });

    }

    private void getData() {
        Bundle extras = getIntent().getExtras();
        int cat;
        if (extras == null) {
            cat = 0;
        } else {
            cat = extras.getInt("Cat");
        }

        switch (cat) {
            case 0:
                modelList.add(new EventsModel("Log IQ","EED Seminar Hall", "With the ace of wits under your sleeve, gear up this Tathva to battle out the most sharp-witted nemeses in this out of the box, hair-raising quiz. Go insane, stop guessing and start being logical. Follow your intellect and reason as they lead your way out of this gruelling labyrinth and earn the title of a mathwiz at Log IQ.\n", R.drawable.events4));
                modelList.add(new EventsModel("Treasure Hunt","DB 207", "Study the maps, understand the surroundings and bring out the natural seeker in you. For Tathva is round the corner and with it comes your own quest to bring back the Golden Fleece. Stay sharp as all you'll have are some clues (you may use a niffler if required) and your wits. Be the first to get to the treasure and you may call it yours but don't panic, \"just seek and ye shall find\"", R.drawable.events2));
                modelList.add(new EventsModel("Inquisito Virtuoso","NLHC 201", "\"Elementary, my dear Watson\"\n" +
                        "When the mind and soul conspires,\n" +
                        "When the eyes meticulously search for hints,\n" +
                        "When even the subconscious mind toils for clues, no crime in this world goes unsolved. However the mysteries at Tathva Inquisito Virtuoso are sure to give even the world's greatest detective a mind boggling time. This Tathva, awaken the Sherlock in you, and prepare to go all out in this war of logic, assumption and observation", R.drawable.events3));
                modelList.add(new EventsModel("Cube Open","NLHC 301,302", "A mind boggling question mark, an idiosyncratic solution and 6 colours that baffle your wits. A twist here, a turn there and a few more of that. Voilà! Your cube is solved. Tathva cube open, the speed cubing event with WCA recognition, welcomes cubers all over the country to showcase their speed cubing skills. So get your fingers moving cause time\'s running out!", R.drawable.events1));
                modelList.add(new EventsModel("Skills N Thrills","NLHC 304", "A pinch of dexterity, a touch of strategy, and plenty of will, wit and grit. A synchrony of these traits is all it takes to champion Skills n Thrills. The very game to churn your brains, this event asks you to crack your way through Sudoku and Checkers puzzles to prove your mettle. The grids are set, the numbers are in place. The game of brains is ready for the race. Join in.\n", R.drawable.about_bg));
                modelList.add(new EventsModel("Log IQ","EED Seminar Hall", "With the ace of wits under your sleeve, gear up this Tathva to battle out the most sharp-witted nemeses in this out of the box, hair-raising quiz. Go insane, stop guessing and start being logical. Follow your intellect and reason as they lead your way out of this gruelling labyrinth and earn the title of a mathwiz at Log IQ.\n", R.drawable.events1));
                modelList.add(new EventsModel("Treasure Hunt","DB 207", "Study the maps, understand the surroundings and bring out the natural seeker in you. For Tathva is round the corner and with it comes your own quest to bring back the Golden Fleece. Stay sharp as all you'll have are some clues (you may use a niffler if required) and your wits. Be the first to get to the treasure and you may call it yours but don't panic, \"just seek and ye shall find\"", R.drawable.events2));
                modelList.add(new EventsModel("Inquisito Virtuoso","NLHC 201", "\"Elementary, my dear Watson\"\n" +
                        "When the mind and soul conspires,\n" +
                        "When the eyes meticulously search for hints,\n" +
                        "When even the subconscious mind toils for clues, no crime in this world goes unsolved. However the mysteries at Tathva Inquisito Virtuoso are sure to give even the world's greatest detective a mind boggling time. This Tathva, awaken the Sherlock in you, and prepare to go all out in this war of logic, assumption and observation", R.drawable.events4));
                modelList.add(new EventsModel("Cube Open","NLHC 301,302", "A mind boggling question mark, an idiosyncratic solution and 6 colours that baffle your wits. A twist here, a turn there and a few more of that. Voilà! Your cube is solved. Tathva cube open, the speed cubing event with WCA recognition, welcomes cubers all over the country to showcase their speed cubing skills. So get your fingers moving cause time\'s running out!", R.drawable.events3));
                modelList.add(new EventsModel("Skills N Thrills","NLHC 304", "A pinch of dexterity, a touch of strategy, and plenty of will, wit and grit. A synchrony of these traits is all it takes to champion Skills n Thrills. The very game to churn your brains, this event asks you to crack your way through Sudoku and Checkers puzzles to prove your mettle. The grids are set, the numbers are in place. The game of brains is ready for the race. Join in.\n", R.drawable.about_bg));

                break;
            case 1:
                modelList.add(new EventsModel("Srishti","MED Seminar Hall", "Ever got an idea that sounded amazing in your head but failed terribly when you told your friends about it? Here at Srishti, meet like minded thinkers, present your ideas to the world and bring them to life because everything big in this world happens from ideas that sound impossible.\n", R.drawable.events1));
                modelList.add(new EventsModel("Blueprint","", "Your brain's been churning, your master plan stands complete and your ideas are blueprinted. What's next on the agenda?\n" +
                        "If you believe you're a prophet of the tech world, on the lookout for a pedestal to present your visions, then Blueprint is your calling. Channel your scholarly divinity towards unearthing solutions to modern day problems and pitch your proposition. This Tathva make your ideas count.\n" +
                        "Only those who have been selected based on their abstract submission can register online.\n", R.drawable.events2));
                modelList.add(new EventsModel("Srishti","MED Seminar Hall", "Ever got an idea that sounded amazing in your head but failed terribly when you told your friends about it? Here at Srishti, meet like minded thinkers, present your ideas to the world and bring them to life because everything big in this world happens from ideas that sound impossible.\n", R.drawable.events1));
                modelList.add(new EventsModel("Blueprint","", "Your brain's been churning, your master plan stands complete and your ideas are blueprinted. What's next on the agenda?\n" +
                        "If you believe you're a prophet of the tech world, on the lookout for a pedestal to present your visions, then Blueprint is your calling. Channel your scholarly divinity towards unearthing solutions to modern day problems and pitch your proposition. This Tathva make your ideas count.\n" +
                        "Only those who have been selected based on their abstract submission can register online.\n", R.drawable.events2));
                modelList.add(new EventsModel("Srishti","MED Seminar Hall", "Ever got an idea that sounded amazing in your head but failed terribly when you told your friends about it? Here at Srishti, meet like minded thinkers, present your ideas to the world and bring them to life because everything big in this world happens from ideas that sound impossible.\n", R.drawable.events1));
                modelList.add(new EventsModel("Blueprint","", "Your brain's been churning, your master plan stands complete and your ideas are blueprinted. What's next on the agenda?\n" +
                        "If you believe you're a prophet of the tech world, on the lookout for a pedestal to present your visions, then Blueprint is your calling. Channel your scholarly divinity towards unearthing solutions to modern day problems and pitch your proposition. This Tathva make your ideas count.\n" +
                        "Only those who have been selected based on their abstract submission can register online.\n", R.drawable.events2));
                break;
            case 2:
                modelList.add(new EventsModel("GSM Labyrinth","Inner Hall Complex", "Power your brains and get your kits ready. This Tathva, we bring to you, the battle of the bots. It's your turn to build your dream land rover using GSM technology. Race against your opponents and keep count of your time because the fastest bot is always prime!\n", R.drawable.events1));
                modelList.add(new EventsModel("Analog IQ","NLHC 302", "In a world driven by electronics, the real challenge isn't making machines think, as much as it is to make ourselves think. So wire up and connect all ideas, as you prepare to put your skills to the test. Quicken the pulse, amplify your thoughts, and buckle up to bring out the analogue signal connoisseur in you. Brace yourselves for three levels of quizzes, tests, and brain wracking simulations as you battle it out with best. After all, we may just be analogues living in a digital world but we've all got a chance to find an ADC.\n", R.drawable.events2));
                modelList.add(new EventsModel("E Racer","DB 206, Embedded Systems Lab", "\"Technology is a word that describes something that doesn't work yet.\" Science and dilatoriness are inseparable, yet man is always eager and passionate to put meticulous effort for scientific growth. Do you believe you have what it takes to assemble and organize complex circuits while racing against the clock? Be a part of E-Racer this Tathva and exploit your dexterity in electronics. Attitude amplified, faults rectified!\n", R.drawable.events4));
                modelList.add(new EventsModel("GSM Labyrinth","Inner Hall Complex", "Power your brains and get your kits ready. This Tathva, we bring to you, the battle of the bots. It's your turn to build your dream land rover using GSM technology. Race against your opponents and keep count of your time because the fastest bot is always prime!\n", R.drawable.events1));
                modelList.add(new EventsModel("Analog IQ","NLHC 302", "In a world driven by electronics, the real challenge isn't making machines think, as much as it is to make ourselves think. So wire up and connect all ideas, as you prepare to put your skills to the test. Quicken the pulse, amplify your thoughts, and buckle up to bring out the analogue signal connoisseur in you. Brace yourselves for three levels of quizzes, tests, and brain wracking simulations as you battle it out with best. After all, we may just be analogues living in a digital world but we've all got a chance to find an ADC.\n", R.drawable.events2));
                modelList.add(new EventsModel("E Racer","DB 206, Embedded Systems Lab", "\"Technology is a word that describes something that doesn't work yet.\" Science and dilatoriness are inseparable, yet man is always eager and passionate to put meticulous effort for scientific growth. Do you believe you have what it takes to assemble and organize complex circuits while racing against the clock? Be a part of E-Racer this Tathva and exploit your dexterity in electronics. Attitude amplified, faults rectified!\n", R.drawable.events4));

                break;
            case 3:
                modelList.add(new EventsModel("Coil Gun","DB 301", "\"I have a strict gun control policy. If there is a gun around, I want to be in control of it.\"\n" +
                        "-Clint Eastwood\n" +
                        "Get ready to exercise both your grey matter and trigger muscles this Tathva, as we give you an opportunity to build and control your own Coil Gun. Blend the techniques of Gauss and Colt as you craft a master weapon and prove that yours is undoubtedly the sassiest gat in town", R.drawable.events1));
                modelList.add(new EventsModel("Accelero-BotX","Auditorium", "Accelerobotx calls out to the robot fanatics who can prove that their bot is the best of the best. Elevate your knowledge of coding, control and coordination. Fight against all odds and establish yourself as the pro. This Tathva, hustle up for a spectacular array of bots and watch yours battle against the others, following your hand gestures. The arena awaits you!\n", R.drawable.events2));
                modelList.add(new EventsModel("Digimania","NLHC 301", "Finding order in chaos is near impossible. In this event, you need to pull off this Herculean task of finding chaos in perfectly ordered circuits. Your keen vision alone cannot propel you to the top. Arm yourselves to the teeth with the knowledge of electronics and logic design. Sharpen your wits and push yourselves because this intellectual battle crowns the brightest contender.\n", R.drawable.events4));
                modelList.add(new EventsModel("Circuit Race","NLHC 303, Electronics Lab", "Circuiteers out there! Get ready for some electric moments this Tathva!\n" +
                        "Designing our circuits is no easy game. If your brain can resist the pressure and yet think quickly, you can make it to the top. Shock us with your skill and team spirit. Remember, accuracy with speed is the yardstick!\n" +
                        "Join this quest, to be the best!", R.drawable.events3));
                modelList.add(new EventsModel("Coil Gun","DB 301", "\"I have a strict gun control policy. If there is a gun around, I want to be in control of it.\"\n" +
                        "-Clint Eastwood\n" +
                        "Get ready to exercise both your grey matter and trigger muscles this Tathva, as we give you an opportunity to build and control your own Coil Gun. Blend the techniques of Gauss and Colt as you craft a master weapon and prove that yours is undoubtedly the sassiest gat in town", R.drawable.events1));
                modelList.add(new EventsModel("Accelero-BotX","Auditorium", "Accelerobotx calls out to the robot fanatics who can prove that their bot is the best of the best. Elevate your knowledge of coding, control and coordination. Fight against all odds and establish yourself as the pro. This Tathva, hustle up for a spectacular array of bots and watch yours battle against the others, following your hand gestures. The arena awaits you!\n", R.drawable.events2));
                modelList.add(new EventsModel("Digimania","NLHC 301", "Finding order in chaos is near impossible. In this event, you need to pull off this Herculean task of finding chaos in perfectly ordered circuits. Your keen vision alone cannot propel you to the top. Arm yourselves to the teeth with the knowledge of electronics and logic design. Sharpen your wits and push yourselves because this intellectual battle crowns the brightest contender.\n", R.drawable.events4));
                modelList.add(new EventsModel("Circuit Race","NLHC 303, Electronics Lab", "Circuiteers out there! Get ready for some electric moments this Tathva!\n" +
                        "Designing our circuits is no easy game. If your brain can resist the pressure and yet think quickly, you can make it to the top. Shock us with your skill and team spirit. Remember, accuracy with speed is the yardstick!\n" +
                        "Join this quest, to be the best!", R.drawable.events3));

                break;
            case 4:
                modelList.add(new EventsModel("The Debugger","NSL", "The tiniest of errors can bring everything crashing down. An uninitialized variable, a missing semi colon. Seemingly harmless mistakes that will come back to haunt you. There is no margin for error in the art of programming. Only the best of the best can step into this barren wasteland of code. Right the wrongs and attain perfection in Debugger.\n", R.drawable.events1));
                modelList.add(new EventsModel("Hack-a-Holic","SSL", "\"The quieter you are, the more you hear.\" This Tathva put your programming proficiency to the test. Eliminate all the bugs embedded in the source code and come up with programs to counter any discrepancies. Protection from incoming threats, detection of inbuilt short comings and diffusion of potential outbreaks; they're all in your job description. Create your own algorithm of success and code your way out of the toughest of problems. Let the games begin!\n", R.drawable.events2));
                modelList.add(new EventsModel("Tux of War","SSL", "Calling all geeks out their shells. If you stray from popular misconceptions where Microsoft and iOS played center stage, you're definitely familiar with Linux. Here’s a three-part event that puts it to the test. Your algorithm to acing this starts with a written test on basic commands. Clear this to progress to the final two levels where your team faces it off with a Linux terminal.\n", R.drawable.events4));
                modelList.add(new EventsModel("The Debugger","NSL", "The tiniest of errors can bring everything crashing down. An uninitialized variable, a missing semi colon. Seemingly harmless mistakes that will come back to haunt you. There is no margin for error in the art of programming. Only the best of the best can step into this barren wasteland of code. Right the wrongs and attain perfection in Debugger.\n", R.drawable.events1));
                modelList.add(new EventsModel("Hack-a-Holic","SSL", "\"The quieter you are, the more you hear.\" This Tathva put your programming proficiency to the test. Eliminate all the bugs embedded in the source code and come up with programs to counter any discrepancies. Protection from incoming threats, detection of inbuilt short comings and diffusion of potential outbreaks; they're all in your job description. Create your own algorithm of success and code your way out of the toughest of problems. Let the games begin!\n", R.drawable.events2));
                modelList.add(new EventsModel("Tux of War","SSL", "Calling all geeks out their shells. If you stray from popular misconceptions where Microsoft and iOS played center stage, you're definitely familiar with Linux. Here’s a three-part event that puts it to the test. Your algorithm to acing this starts with a written test on basic commands. Clear this to progress to the final two levels where your team faces it off with a Linux terminal.\n", R.drawable.events4));

                break;
            case 5:
                modelList.add(new EventsModel("Bob the Builder","NLHC 201,204", "If plans and elevations are the building blocks of your ecosystem and the thought of buildings and constructions makes your eyes light up, Tathva brings you the test of your world through Bob the Builder. Be part of an indented extravaganza and prove your wits. Given any real life situation, do you have what it takes to build the perfect plan? Taking into account all real time circumstances, can your plan survive? All it takes is a boardroom presentation of your plan to establish your ideas as the best.\n", R.drawable.events1));
                modelList.add(new EventsModel("CAD Art","NLHC 202,CAD Lab", "Calling all Auto-CAD enthusiasts to conceptualize and design their own prototypes using the CAD software. Unleash the art to make an ingenious design that's more than just a few tricks to the eye. This Tathva '17, showcase your talents on a creative stage, open exclusively for technical perf足ormers of all levels of expertise. Master the skill of creating aesthetically pleasing visual elements and design the face of tomorrow.\n", R.drawable.events2));
                modelList.add(new EventsModel("Descartes Square","NLHC 201,Football Ground", "\"God used beautiful mathematics in creating the world.\"\n" +
                        "All you have is a stick, can you measure the size of the earth? Then step right in and be a part of Descartes Square this Tathva. Flaunt your surveying abilities and geometric expertise to prove who is the best in the game. Equip yourself with theodolites, dumpy levels, tapes, chains and rods to tackle and delineate the terrain.\n" +
                        "Think logically. Measure accurately.", R.drawable.events4));
                modelList.add(new EventsModel("Linkidge","NLHC 103", "They say architecture is music in space, frozen at the spot, an art that calls for intricate design and imagery. Sometimes the best ideas are born out of the simplest of things. So we present to you the very dais to bring out yours.\n" +
                        "Unlimited ice cream sticks. Five creative minds. One structure.\n" +
                        "Unleash your design this Tathva, at 'Linkidge'.\n", R.drawable.events3));
                modelList.add(new EventsModel("Skyscrapers","NLHC 201", "Innovation distinguishes between a leader and a follower. Cease to follow and start to lead by putting your abstract ideas into concrete actions. At Tathva'17, 'Skyscrapers' invites all emerging Civil engineers of today, to begin designing the face of tomorrow. Start from rock bottom and create a futuristic skyscraper of your imagination, using nothing but Popsicle sticks, adhesives and paper. Put your reasoning mind to the ultimate test by competing with the best engineers out there, to create a scraper than can surmount all obstacles.\n", R.drawable.about_bg));
                modelList.add(new EventsModel("Bob the Builder","NLHC 201,204", "If plans and elevations are the building blocks of your ecosystem and the thought of buildings and constructions makes your eyes light up, Tathva brings you the test of your world through Bob the Builder. Be part of an indented extravaganza and prove your wits. Given any real life situation, do you have what it takes to build the perfect plan? Taking into account all real time circumstances, can your plan survive? All it takes is a boardroom presentation of your plan to establish your ideas as the best.\n", R.drawable.events1));
                modelList.add(new EventsModel("CAD Art","NLHC 202,CAD Lab", "Calling all Auto-CAD enthusiasts to conceptualize and design their own prototypes using the CAD software. Unleash the art to make an ingenious design that's more than just a few tricks to the eye. This Tathva '17, showcase your talents on a creative stage, open exclusively for technical perf足ormers of all levels of expertise. Master the skill of creating aesthetically pleasing visual elements and design the face of tomorrow.\n", R.drawable.events2));
                modelList.add(new EventsModel("Descartes Square","NLHC 201,Football Ground", "\"God used beautiful mathematics in creating the world.\"\n" +
                        "All you have is a stick, can you measure the size of the earth? Then step right in and be a part of Descartes Square this Tathva. Flaunt your surveying abilities and geometric expertise to prove who is the best in the game. Equip yourself with theodolites, dumpy levels, tapes, chains and rods to tackle and delineate the terrain.\n" +
                        "Think logically. Measure accurately.", R.drawable.events4));
                modelList.add(new EventsModel("Linkidge","NLHC 103", "They say architecture is music in space, frozen at the spot, an art that calls for intricate design and imagery. Sometimes the best ideas are born out of the simplest of things. So we present to you the very dais to bring out yours.\n" +
                        "Unlimited ice cream sticks. Five creative minds. One structure.\n" +
                        "Unleash your design this Tathva, at 'Linkidge'.\n", R.drawable.events3));

                break;
            case 6:
                modelList.add(new EventsModel("Cheo Propello","Outside Auditorium", "Do you have the potential to tackle obstacles with the right chemistry? Unleash the mad scientist in you this Tathva! Design a self-propelled vehicle that runs on a chemical reaction and beat your opponents on the race track. Innovate, ignite, and race your way to glory!\n", R.drawable.events1));
                modelList.add(new EventsModel("Concorso","NLHC 102", "The tables are set. The stage awaits you. Get your neurons cracking and slam the buzzers with fury as Tathva ’17 proudly presents Concorso, the place to be if you’ve got the chemistry and the grey matter to be crowned Crystal King . A sound knowledge of chemical engineering and its applications is all you need to lay your hands on the silverware.\n", R.drawable.events2));
                modelList.add(new EventsModel("Interrupter","Chemical Technology", "Chemistry and Circuitry are the Yin-Yang of our lives. If you think you can master the technique of controlling electrical circuits by chemical means, then this is your battlefield. Battle it out with chemicals and wires to crown yourself as the 'Interrupter' this Tathva’17.\n", R.drawable.events4));
                modelList.add(new EventsModel("Cheo Propello","Outside Auditorium", "Do you have the potential to tackle obstacles with the right chemistry? Unleash the mad scientist in you this Tathva! Design a self-propelled vehicle that runs on a chemical reaction and beat your opponents on the race track. Innovate, ignite, and race your way to glory!\n", R.drawable.events1));
                modelList.add(new EventsModel("Concorso","NLHC 102", "The tables are set. The stage awaits you. Get your neurons cracking and slam the buzzers with fury as Tathva ’17 proudly presents Concorso, the place to be if you’ve got the chemistry and the grey matter to be crowned Crystal King . A sound knowledge of chemical engineering and its applications is all you need to lay your hands on the silverware.\n", R.drawable.events2));

                break;
            case 7:
                modelList.add(new EventsModel("Aerogami","Auditorium", "Put your aerodynamic prowess to the test by making the best paper airplane, at Aerogami. Prepare to take your favourite childhood memory to a whole new level by competing with like-minded individuals who are passionate about aeromodelling. Get started on a unique journey and take off against the winds, just like a paper plane would.\n", R.drawable.events1));
                modelList.add(new EventsModel("Aerogami","Auditorium", "Put your aerodynamic prowess to the test by making the best paper airplane, at Aerogami. Prepare to take your favourite childhood memory to a whole new level by competing with like-minded individuals who are passionate about aeromodelling. Get started on a unique journey and take off against the winds, just like a paper plane would.\n", R.drawable.events1));
                modelList.add(new EventsModel("Aerogami","Auditorium", "Put your aerodynamic prowess to the test by making the best paper airplane, at Aerogami. Prepare to take your favourite childhood memory to a whole new level by competing with like-minded individuals who are passionate about aeromodelling. Get started on a unique journey and take off against the winds, just like a paper plane would.\n", R.drawable.events1));

                break;
            case 9:
                modelList.add(new EventsModel("Artha","Auditorium", "Are you a competent prodigal wiz kid with a knack for business trivia and everything techy? Artha has it all covered, now better than ever. Knock out your brains and win your way out of the quiz to get hold of amazing prizes!\n", R.drawable.events1));
                modelList.add(new EventsModel("Kick Off","Bhaskara Hall", "A true lover of sport doesn't have to train for hours, or jump fences chasing their heroes, this one's for those of you who also love to cheer for their team behind a bowl of popcorn in the comforts of their couch.\n" +
                        "This Tathva, lace up your shoes, fasten your helmets and step into the courts to showcase your expertise in a quiz that's all about sports and games. Be ready to defend your title as a know-it-all, because this one's a battle of the fanatics. Kick off begins in 3..2...1..\n", R.drawable.events2));
                modelList.add(new EventsModel("SpEnt","Bhaskara Hall", "What is life without competition and frivolity? Entertainment is upgraded by the minute, so can you keep up? Come and find out this Tathva in the Sports and Entertainment Quiz.\n", R.drawable.events4));
                modelList.add(new EventsModel("Prahelika","MED Seminar Hall", "Knowledge is power. This has never rung truer than in the quizzing world. It's survival of the smartest, so you have got to bring your A game. If you know all the answers, you hold all the cards, nothing else to it. Sharpen those grey cells and prepare for an intellectual extravaganza like no other, covering every topic under the sun.\n", R.drawable.events3));
                modelList.add(new EventsModel("Samasya","Auditorium", "Calling out all the youngsters with quizzing minds.\n" +
                        "The stage is set, curtains drawn and questions ready to be fired. In a race where wit and spontaneity are your only companions and where time is your biggest enemy, brace yourself for every bombshell dropped by the quiz master. Enhance your graymatter because Samasya is here!\n", R.drawable.about_bg));
                modelList.add(new EventsModel("Artha","Auditorium", "Are you a competent prodigal wiz kid with a knack for business trivia and everything techy? Artha has it all covered, now better than ever. Knock out your brains and win your way out of the quiz to get hold of amazing prizes!\n", R.drawable.events1));
                modelList.add(new EventsModel("Kick Off","Bhaskara Hall", "A true lover of sport doesn't have to train for hours, or jump fences chasing their heroes, this one's for those of you who also love to cheer for their team behind a bowl of popcorn in the comforts of their couch.\n" +
                        "This Tathva, lace up your shoes, fasten your helmets and step into the courts to showcase your expertise in a quiz that's all about sports and games. Be ready to defend your title as a know-it-all, because this one's a battle of the fanatics. Kick off begins in 3..2...1..\n", R.drawable.events2));
                modelList.add(new EventsModel("SpEnt","Bhaskara Hall", "What is life without competition and frivolity? Entertainment is upgraded by the minute, so can you keep up? Come and find out this Tathva in the Sports and Entertainment Quiz.\n", R.drawable.events4));
                modelList.add(new EventsModel("Prahelika","MED Seminar Hall", "Knowledge is power. This has never rung truer than in the quizzing world. It's survival of the smartest, so you have got to bring your A game. If you know all the answers, you hold all the cards, nothing else to it. Sharpen those grey cells and prepare for an intellectual extravaganza like no other, covering every topic under the sun.\n", R.drawable.events3));

                break;
            case 8:
                modelList.add(new EventsModel("Albatross","Academic block,Football Ground", "Humanity has been in love with flying ever since the first aircraft took off at Kitty Hawk. So, for all of you with that passionate love brewing in your soul, Tathva in association with The Aero Unwired Team of NITC, presents to you the perfect platform to direct that passion into work. Design, build and test gliders in their speed, stability, agility, and landing capabilities.\n", R.drawable.events1));
                modelList.add(new EventsModel("Aqua GT","Offshore Lab", "\"Be it the wind, rain or high tides, nothing can deter those who have the courage to lose sight of the shore\". If that is your mantra then aquaGT will be your game to ace. Forge an RC boat that can parry the odds. If your machine is agile and protean to tackle any twist and turn, then rest assured you'll win this game with panache. So clear the decks to triumph over the rest.\n", R.drawable.events2));
                modelList.add(new EventsModel("Aqua Strike","Football Ground", "3.....2.....1.....Lift Off\n" +
                        "Welcome to Aqua strike. Your mission should you choose to accept it...is to build an unrivalled water rocket that can survive the trials because when it comes down to the seas, only the smartest fish survive. Speed, Range, Accuracy, you've got to excel in them all.\n" +
                        "Rocketeer, do you accept?", R.drawable.events4));
                modelList.add(new EventsModel("Contraption","MB 301", "A daunting task needs simplification, but if the task is too simple you toughen it up for the fun of it. Are you someone who appreciates a fair challenge? Well if so, get ready to raise the bars with CONTRAPTION; where you impress the judges by a simple stroke of creativity, put it together with a pinch of hard work, and present it with passion. May the most complicated contraption win.\n", R.drawable.events3));
                modelList.add(new EventsModel("Hoverdrive","Tennis Ground", "The track is set. The engines have roared to a start. The legendary race is a mere whistle blow away.\n" +
                        "Bring out the engineer in you as you design your hovercraft and test it for speed, manoeuvrability and handling on challenging terrains like sand, water and gravel.\n" +
                        "This Tathva witness a race like no other. See you at the finish line, if you can make it!\n", R.drawable.about_bg));
                modelList.add(new EventsModel("Machnascene","DB 310,Central Workshop", "\"Bolt to the nut\n" +
                        "Spark to the plug\n" +
                        "Key to the starter\n" +
                        "Piston to the cylinder\n" +
                        "Engine to your life.\"\n" +
                        "If that is what Mechanical Engineering is to you, then Tathva offers you the ideal platform to showcase your love for machines. Can you assemble something incredible from scratch while racing against the clock?\n" +
                        "Machnascene sets a jigsaw puzzle in front of you. Display your skills at perceiving and putting together the conundrum with no missing pieces.", R.drawable.events1));
                modelList.add(new EventsModel("Mechtrakhi","NLHC 202, Football Ground", "If you think that you've got a sharp mind, pair that up with sharp tools and bring out the mechanic in you. With the resources that you need, can you engineer the best machine for the given task, on the spot? This Tathva, brace yourselves, and be a part of Mechthraki. May the best machine win.\n", R.drawable.events2));
                modelList.add(new EventsModel("Mindkraft","DB 307,Football Ground", "Does the exhilaration of solving problems make you high? Does your mind crave to celebrate its ingenuity and rationality?\n" +
                        "This one's for you. An arena for the battle of the minds, with intellect and efficacy being the most lethal of weapons. So, explore and ideate to rise above the rest.\n", R.drawable.events4));

                modelList.add(new EventsModel("Albatross","Academic block,Football Ground", "Humanity has been in love with flying ever since the first aircraft took off at Kitty Hawk. So, for all of you with that passionate love brewing in your soul, Tathva in association with The Aero Unwired Team of NITC, presents to you the perfect platform to direct that passion into work. Design, build and test gliders in their speed, stability, agility, and landing capabilities.\n", R.drawable.events1));
                modelList.add(new EventsModel("Aqua GT","Offshore Lab", "\"Be it the wind, rain or high tides, nothing can deter those who have the courage to lose sight of the shore\". If that is your mantra then aquaGT will be your game to ace. Forge an RC boat that can parry the odds. If your machine is agile and protean to tackle any twist and turn, then rest assured you'll win this game with panache. So clear the decks to triumph over the rest.\n", R.drawable.events2));
                modelList.add(new EventsModel("Aqua Strike","Football Ground", "3.....2.....1.....Lift Off\n" +
                        "Welcome to Aqua strike. Your mission should you choose to accept it...is to build an unrivalled water rocket that can survive the trials because when it comes down to the seas, only the smartest fish survive. Speed, Range, Accuracy, you've got to excel in them all.\n" +
                        "Rocketeer, do you accept?", R.drawable.events4));
                modelList.add(new EventsModel("Contraption","MB 301", "A daunting task needs simplification, but if the task is too simple you toughen it up for the fun of it. Are you someone who appreciates a fair challenge? Well if so, get ready to raise the bars with CONTRAPTION; where you impress the judges by a simple stroke of creativity, put it together with a pinch of hard work, and present it with passion. May the most complicated contraption win.\n", R.drawable.events3));
                modelList.add(new EventsModel("Hoverdrive","Tennis Ground", "The track is set. The engines have roared to a start. The legendary race is a mere whistle blow away.\n" +
                        "Bring out the engineer in you as you design your hovercraft and test it for speed, manoeuvrability and handling on challenging terrains like sand, water and gravel.\n" +
                        "This Tathva witness a race like no other. See you at the finish line, if you can make it!\n", R.drawable.about_bg));

                break;
            case 10:
                modelList.add(new EventsModel("Interface-Startup","Bhaskara Hall", "Have you made it BIG yet? Here’s a chance to turn all of the mind-blogging ideas into a reality. It’s time to release your inner Boss-man. Tathva ’17 is presenting you a platform to showcase your entrepreneurship skills. All you have to do is gather your ideas and prepare a blueprint of your Big Plan. The most intriguing ideas gets their Big Thinker professional guidance via online mentoring and a helping hand to lay groundwork for kick-starting their dream. So, what are you waiting for? Here’s the ticket to make your way into the business world. Don’t miss it!\n Logon to www.tathva.org/interface for more details", R.drawable.events1));
                modelList.add(new EventsModel("Alcestis","NLHC 202", "Some people are just born with the instinct to lead! If you have the right demeanour to become a successful and accomplished manager, we got just the thing to test you out. Alcestis, the best manager event is our way to see how far you can manage to go to mark your name in the hall of fame.\n", R.drawable.events2));
                modelList.add(new EventsModel("Board Room","NLHC 303", "A manager does things right, and a leader does the right things. Do you have the wits to do both simultaneously? If yes, then the 'Board Room' is where you belong! The trick of the trade is having the ability to make decisions accurately, solve problems cleverly, and make use of time cautiously. The key to achieving success is to assemble a strong and stable team that can sell anything under the sky. So, adjust your collar and straighten your tie, for this Tathva'17, the 'Board Room' will open once again.\n", R.drawable.events4));
                modelList.add(new EventsModel("Interface-Startup","Bhaskara Hall", "Have you made it BIG yet? Here’s a chance to turn all of the mind-blogging ideas into a reality. It’s time to release your inner Boss-man. Tathva ’17 is presenting you a platform to showcase your entrepreneurship skills. All you have to do is gather your ideas and prepare a blueprint of your Big Plan. The most intriguing ideas gets their Big Thinker professional guidance via online mentoring and a helping hand to lay groundwork for kick-starting their dream. So, what are you waiting for? Here’s the ticket to make your way into the business world. Don’t miss it!\n Logon to www.tathva.org/interface for more details", R.drawable.events1));
                modelList.add(new EventsModel("Alcestis","NLHC 202", "Some people are just born with the instinct to lead! If you have the right demeanour to become a successful and accomplished manager, we got just the thing to test you out. Alcestis, the best manager event is our way to see how far you can manage to go to mark your name in the hall of fame.\n", R.drawable.events2));
                modelList.add(new EventsModel("Board Room","NLHC 303", "A manager does things right, and a leader does the right things. Do you have the wits to do both simultaneously? If yes, then the 'Board Room' is where you belong! The trick of the trade is having the ability to make decisions accurately, solve problems cleverly, and make use of time cautiously. The key to achieving success is to assemble a strong and stable team that can sell anything under the sky. So, adjust your collar and straighten your tie, for this Tathva'17, the 'Board Room' will open once again.\n", R.drawable.events4));

                break;
            case 11:
                modelList.add(new EventsModel("Amazed","Inside Hall Complex", "Is your robot a slick competitor? Here's an event combining the excitement of sport and rigors of science and technology. Navigate your companion out of our maze like a pro; so ready your contraption and prepare to power through this Tathva in Amazed!\n", R.drawable.events1));
                modelList.add(new EventsModel("Collision Course","Inside Hall Complex", "Arm yourselves to enter the battlefield; take it out on your worst rivals. Only this time, remould your weapons into bots.\n" +
                        "Forge the deadliest robot out of that scrapped piece of metal and declare war on other robots as you manoeuvre your way to the top in this clash of droids. This Tathva, send out sparks as you gnaw and scratch, and watch your opponent get smashed!\n", R.drawable.events2));
                modelList.add(new EventsModel("Death Race","Basketball Court", "This event is not for the faint hearted. But if you have a will of steel, then this punishing gauntlet will be right up your alley. The weeks of hard work and dedication may not pay off. But it's the rush of adrenaline that keeps you coming back for more. A gruelling course has been set that is sure to have all you off-road maniacs grinning with delight. After all, we know you guys love a challenge. The carnage will be intense and only a handful will have the honour of saying, “I made it through hell and back.\"\n", R.drawable.events4));
                modelList.add(new EventsModel("Dirt Race","Tennis Court", "Riding yourself through ditches and trenches may be done, but can you do the same with a bot?\n" +
                        "We've laid out the tracks, see if you can beat it along with the rest of them. If speed gets you ahead, a crash slows you down. So only the ultimate robotic creation gets to win prizes and take home glory. So this Tathva show up with your bot and race with the best in the country, for sometimes it's all about winning.\n", R.drawable.events3));
                modelList.add(new EventsModel("League of Machines","Inside Hall Complex", "The winds of exhilaration have descended. The machines have taken positions. The field is set.\n" +
                        "Prepare for combat because this is no ordinary soccer game. The pitch is all your robot's and it's under your control. Prove your mettle in the field to make your match count.\n" +
                        "This Tathva, witness your bots go for the goal at the 'League of Machines'.\n", R.drawable.about_bg));
                modelList.add(new EventsModel("Schwimmwagen","Beside Volleyball Court", "We all had our faces lit up with amazement when we saw Indiana Jones ride down an Amazonian waterfall, in The Schimmwagen. And it gave us all, a dream and an inspiration, to make one. Schimmwagen, as aptly titled, is your platform to build, and showcase the best All Terrain Vehicle that can be engineered. Compete in challenging amphibious tracks, realize your childhood dreams and prove your machine the best!\n", R.drawable.events1));
                modelList.add(new EventsModel("Transporter","Inside Hall Complex", "Transportation is a tricky business, one where not just the destination but also the path you choose will affect your outcome . Despite the revolutions in transportation technology it is said, \"the rider is only as good as his ride.\" Bring your ride to life and take your brainchild on one last ride in the arena that defies all laws to become THE Transporter.\n", R.drawable.events2));

                modelList.add(new EventsModel("Amazed","Inside Hall Complex", "Is your robot a slick competitor? Here's an event combining the excitement of sport and rigors of science and technology. Navigate your companion out of our maze like a pro; so ready your contraption and prepare to power through this Tathva in Amazed!\n", R.drawable.events1));
                modelList.add(new EventsModel("Collision Course","Inside Hall Complex", "Arm yourselves to enter the battlefield; take it out on your worst rivals. Only this time, remould your weapons into bots.\n" +
                        "Forge the deadliest robot out of that scrapped piece of metal and declare war on other robots as you manoeuvre your way to the top in this clash of droids. This Tathva, send out sparks as you gnaw and scratch, and watch your opponent get smashed!\n", R.drawable.events2));
                modelList.add(new EventsModel("Death Race","Basketball Court", "This event is not for the faint hearted. But if you have a will of steel, then this punishing gauntlet will be right up your alley. The weeks of hard work and dedication may not pay off. But it's the rush of adrenaline that keeps you coming back for more. A gruelling course has been set that is sure to have all you off-road maniacs grinning with delight. After all, we know you guys love a challenge. The carnage will be intense and only a handful will have the honour of saying, “I made it through hell and back.\"\n", R.drawable.events4));
                modelList.add(new EventsModel("Dirt Race","Tennis Court", "Riding yourself through ditches and trenches may be done, but can you do the same with a bot?\n" +
                        "We've laid out the tracks, see if you can beat it along with the rest of them. If speed gets you ahead, a crash slows you down. So only the ultimate robotic creation gets to win prizes and take home glory. So this Tathva show up with your bot and race with the best in the country, for sometimes it's all about winning.\n", R.drawable.events3));

                break;
            case 12:
                modelList.add(new EventsModel("Praajna","DB 319", "Science is like magic. A few sparks here and a little adventure later, something revolutionary is created. But the difference about science, is that you control what happens, you decide what to do. Praajna brings you face to face with in-situ problems that will pulverize your grey matter. Where innovation and practically comes first and foremost. If you’ve got the magic in your fingertips then we are giving you the opportunity to let it free\n", R.drawable.events4));
                modelList.add(new EventsModel("Project Expo","DB 306", "In this era of fast paced technological development, man and machines go hand in hand. Every idea and innovation is welcomed with an open mind. As Robin Sharma so rightly said, “Dreamers are mocked as impractical. The truth is they are the most practical as their innovations lead to progress and a better way of life for all of us.” Project expo calls out to the dreamer in every student. Here is a chance to change the world, one idea at a time.\n", R.drawable.events3));
                modelList.add(new EventsModel("Praajna","DB 319", "Science is like magic. A few sparks here and a little adventure later, something revolutionary is created. But the difference about science, is that you control what happens, you decide what to do. Praajna brings you face to face with in-situ problems that will pulverize your grey matter. Where innovation and practically comes first and foremost. If you’ve got the magic in your fingertips then we are giving you the opportunity to let it free\n", R.drawable.events4));
                modelList.add(new EventsModel("Project Expo","DB 306", "In this era of fast paced technological development, man and machines go hand in hand. Every idea and innovation is welcomed with an open mind. As Robin Sharma so rightly said, “Dreamers are mocked as impractical. The truth is they are the most practical as their innovations lead to progress and a better way of life for all of us.” Project expo calls out to the dreamer in every student. Here is a chance to change the world, one idea at a time.\n", R.drawable.events3));
                modelList.add(new EventsModel("Praajna","DB 319", "Science is like magic. A few sparks here and a little adventure later, something revolutionary is created. But the difference about science, is that you control what happens, you decide what to do. Praajna brings you face to face with in-situ problems that will pulverize your grey matter. Where innovation and practically comes first and foremost. If you’ve got the magic in your fingertips then we are giving you the opportunity to let it free\n", R.drawable.events4));
                modelList.add(new EventsModel("Project Expo","DB 306", "In this era of fast paced technological development, man and machines go hand in hand. Every idea and innovation is welcomed with an open mind. As Robin Sharma so rightly said, “Dreamers are mocked as impractical. The truth is they are the most practical as their innovations lead to progress and a better way of life for all of us.” Project expo calls out to the dreamer in every student. Here is a chance to change the world, one idea at a time.\n", R.drawable.events3));

                break;
        }
        EventsCardAdapter eventsAdapter = new EventsCardAdapter(modelList, this);
        swipeCardsView.setAdapter(eventsAdapter);
    }


}
